# .github/workflows/main.yml

# ワークフローの名前
name: Deploy FunConnect to GitHub Pages

# どのイベントでワークフローを実行するか
on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

  # 手動でワークフローを実行するためのオプション（任意）
  workflow_dispatch:

# ジョブの定義
jobs:
  # ビルドしてデプロイするジョブ
  build-and-deploy:
    runs-on: ubuntu-latest # ジョブを実行する環境 (Linux)

    steps:
      # Gitリポジトリをチェックアウト（コードをダウンロード）
      - name: Checkout repository
        uses: actions/checkout@v3

      # GitHub Pagesにデプロイするアクション
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # GitHub Pagesデプロイ用のAction
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHubが自動で提供するトークン
          publish_dir: ./funconnect　# どのディレクトリを公開するか。今回はリポジトリのルート（index.htmlがある場所）
